version: "3.8"

services:
  api:
    build: ./app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - RAILWAY_ENVIRONMENT=development
    volumes:
      - api_data:/app/data
    command: python run_server.py

  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - api
    command: npm run dev

volumes:
  api_data:
