[project]
name = "current"

# --- API service (FastAPI) ---
[[services]]
name = "api"
root = "app"
start = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"

# --- WEB service (Next.js) ---
[[services]]
name = "web"
root = "web"
build = "npm ci && npm run build"
start = "npm run start"