[project]
name = "current"

# --- API service (FastAPI) ---
[[services]]
name = "api"
root = "app"
start = "python run_server.py"

# --- WEB service (Next.js) ---
[[services]]
name = "web"
root = "web"
build = "npm ci && npm run build"
start = "npm run start"