[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = [
  'pip3 install -r requirements.txt'
]

[phases.build]
cmds = ['mkdir -p data', 'ls -la /app', 'pwd', 'which python3']

[start]
cmd = 'python run_server.py'