[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install -r requirements.txt'
]

[phases.build]
cmds = ['mkdir -p data']

[start]
cmd = 'python start_server.py'