[phases.setup]
nixPkgs = ['python311', 'pip']

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install -r requirements.txt'
]

[phases.build]
cmds = [
  'mkdir -p data',
  'python -c "import uvicorn; print(f\"Uvicorn installed at: {uvicorn.__file__}\")"',
  'which python',
  'python --version'
]

[start]
cmd = 'python start_server.py'