[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
cmds = [
  'python -m pip install --upgrade pip',
  'python -m pip install -r requirements.txt'
]

[phases.build]
cmds = ['mkdir -p data']

[start]
cmd = 'python start_server.py'