[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/ready"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "python3 -m uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"

[variables]
PORT = "8000"
PYTHONPATH = "/app"