[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/ready"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "python start_server.py"

[variables]
PORT = "8000"
PYTHONPATH = "/app"